import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Header/Navbar";
import Footer from "@/component/Footer/Footer";

import Support from "@/component/Footer/Support";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "shop.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main>
          {children}
        </main>
          <Support></Support>
        <Footer></Footer>
        </body>
    </html>
  );
}
